# Generated by Django 3.0.3 on 2020-06-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0003_auto_20200607_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='password',
        ),
    ]
