# Generated by Django 3.0.3 on 2020-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0004_remove_information_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='password',
            field=models.CharField(default='12345', max_length=32),
        ),
    ]
