# Generated by Django 3.0.3 on 2020-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0005_information_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='information',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
