# Generated by Django 3.0.3 on 2020-06-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0006_auto_20200609_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
