# Generated by Django 3.0.3 on 2020-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0007_auto_20200609_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
