# Generated by Django 3.0.3 on 2020-06-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0008_auto_20200609_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informations',
            new_name='Information',
        ),
    ]
